FY-77/사이트-맵-문서-작성
42ForYou/frontend pull request #3
Opened 2024-01-20 10:28 UTC by Yonaim

사이트 맵(URL 맵) 문서 작성하였습니다.
기획이 전부 이루어진 것이 아니기 때문에 차후에 변경될 수 있습니다.
이 점 감안하여 봐주시면 감사합니다.
현 단계에서 작성할 수 있는 정보는 가능한 적었습니다.

2024-01-20 10:53 UTC, JinMuGo requested changes
single line comment를 확인해주세요!

2024-01-20 10:53 UTC, JinMuGo commented on docs/sitemap.md
> +- 게임 방 (1대1) 페이지
milestone1에 게임 방 1대 1 페이지의 구성 요소를 넣기로 하였으니 추가 해 주세요!

2024-01-20 10:53 UTC, JinMuGo commented on docs/sitemap.md
> +- 게임 방 (토너먼트) 페이지
1대 1 페이지와 동일한 이유로 코멘트 남깁니다

2024-01-22 06:10 UTC, Yonaim commented
문서 수정하였습니다 재리뷰 부탁드립니다! @JinMuGo

2024-01-22 07:49 UTC, JinMuGo approved these changes
milestone1단계에서는 이정도면 충분할 것 같습니다!

2024-01-22 07:58 UTC, merged